version: "3"
services:
  jupyterlab-docker:
    container_name: jupyterlab-docker
    build:
      context: ./jupyterlab
      dockerfile: Dockerfile
    restart: always
    entrypoint: >
      jupyter-lab
      --allow-root
      --ip=0.0.0.0
      --port=8888
      --no-browser
      --NotebookApp.token=''
      --notebook-dir=/workspace
    networks:
      - default_network
    ports:
      - ${PORTS}:8888
    volumes:
      - ${PWD}/jupyterlab/config:/root/.jupyter
      - ${PWD}/workspace:/workspace

networks:
  default_network:
    external: true