version: "3"
services:
  jupyterlab-docker:
    container_name: jupyterlab-docker
    build:
      context: ./jupyterlab
      dockerfile: Dockerfile
    restart: always
    entrypoint: >
      jupyter-lab
      --allow-root
      --ip=0.0.0.0
      --port=8888
      --no-browser
      --NotebookApp.token=''
      --notebook-dir=/workspace
    networks:
      - nginxproxymanager_default
    ports:
      - 18888:8888
    volumes:
      - /docker/docjup/jupyterlab/config:/root/.jupyter
      - /docker/docjup/workspace:/workspace

networks:
  nginxproxymanager_default:
    external: true